APP/urls.py
from django.urls import path

from .views import (
    MiddagListView,
    MiddagDeleteView,
    MiddagUpdateView,
    MiddagCreateView,
    MiddagDetailView,
)

urlpatterns = [
    path('', MiddagListView.as_view(), name='APP-home'),
    path('middag/<int:pk>/', MiddagDetailView.as_view(), name='middag-detail'),
    path('middag/new/', MiddagCreateView.as_view(), name='middag-create'),
    path('middag/<int:pk>/update', MiddagUpdateView.as_view(), name='middag-update'),
    path('middag/<int:pk>/delete', MiddagDeleteView.as_view(), name='middag-delete'),
]

middagsdeling/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('send/', user_views.send_message, name='send_message'),
    path('messages/', user_views.user_messages, name='messages'),
    path('home/', include('APP.urls')),
]

APP/models.py
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from multiselectfield import MultiSelectField

sharing_choices = [
        ('ja', 'Ja'),
        ('no', 'Nei'),
]

allergener_choices =[
        ('GLUTEN', 'Gluten'),
        ('LAKTOSE', 'Laktose'),
        ('EGG', 'Egg'),
        ('NØTTER', 'Nøtter'),
        ('INGEN', 'Ingen'),
]


class Middag(models.Model):
    title = models.CharField(max_length=125)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    guests = models.PositiveSmallIntegerField()
    sharing = models.CharField(
        max_length=2,
        choices=sharing_choices,
        default='ja',
    )
    sharing_cost = models.PositiveSmallIntegerField(blank=True, null=True)
    allergener = MultiSelectField(choices=allergener_choices)
    address = models.CharField(max_length=200, default=None)
    postnr = models.PositiveSmallIntegerField(default=None)
    poststed = models.CharField(max_length=200, default=None)
    date_of_dinner = models.DateTimeField(default=None)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('middag-detail', kwargs={'pk': self.pk})

users/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

from APP.models import Middag
from multiselectfield import MultiSelectField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} Profile'


class Message(models.Model):
    User = settings.AUTH_USER_MODEL
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    to_user = models.ForeignKey(User, related_name='receiver', on_delete=models.CASCADE)
    message = models.TextField()

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Message


class UserRegisterForm(UserCreationForm):
    name = forms.CharField(label='Fullt navn')
    ALLERGIES_CHOICES = [
        ('gluten', 'Gluten'),
        ('laktose', 'Laktose'),
        ('egg', 'Egg'),
        ('nøtter', 'Nøtter'),
        ('ingen', 'Ingen'),
    ]
    allergies = forms.MultipleChoiceField(
        required=True,
        widget=forms.CheckboxSelectMultiple,
        choices=ALLERGIES_CHOICES
    )
    address = forms.CharField(label='Gatenavn og husnummer')
    postnr = forms.IntegerField(label='Postnummer')
    poststed = forms.CharField(label='Sted')

    class Meta:
        model = User
        fields = ['username', 'name', 'allergies', 'address', 'postnr', 'poststed', 'password1', 'password2']


class SendMessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['title', 'to_user', 'message']

APP/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Middag


def home(request):
    context = {
        'middager': Middag.objects.all()
    }
    return render(request, 'APP/home.html', context)


class MiddagListView(ListView):
    model = Middag
    template_name = 'APP/home.html'
    context_object_name = 'middager'
    ordering = ['-date_posted']


class MiddagDetailView(DetailView):
    model = Middag


class MiddagCreateView(LoginRequiredMixin, CreateView):
    model = Middag
    fields = ['title', 'content', 'guests', 'sharing', 'allergener', 'sharing_cost', 'address', 'postnr', 'poststed', 'date_of_dinner']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class MiddagUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Middag
    fields = ['title', 'content', 'guests', 'sharing', 'allergener', 'sharing_cost', 'address', 'postnr', 'poststed', 'date_of_dinner']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class MiddagDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Middag
    success_url = '/home'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


#TODO: Returnere få til å vise view middag_confirm_join

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, SendMessageForm
from .models import Message


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            name = form.cleaned_data.get('name')
            messages.success(request, f'Account created for {name}!')
            return redirect('APP-home')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


def send_message(request):
    if request.method == 'POST':
        form = SendMessageForm(request.POST)
        if form.is_valid():
            fs = form.save(commit=False)
            fs.author = request.user
            fs.save()
            return redirect('APP-home')
    else:
        form = SendMessageForm()
    return render(request, 'users/send_message.html', {'form': form})


def user_messages(request):
    context = {
        'messages': Message.objects.filter(author=request.user) | Message.objects.filter(to_user=request.user)
    }
    return render(request, 'users/messages.html', context)


@login_required
def profile(request):
    return render(request, 'users/profile.html')

APP/templates/APP/base.html
{% load static %}
<!DOCTYPE html>
<html lang="no">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static '/css/create-post.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/middag_detail.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/middag_confirm_delete.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/middag_confirm_join.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/home.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/profile.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/send_message.css' %}">

    {% if title %}
        <title>Middagsdeling - {{ title }}</title>
    {% else %}
        <title>Middagsdeling</title>
    {% endif %}
</head>
<body>
    <style type="text/css" media="screen">

        @import url('https://fonts.googleapis.com/css?family=Montserrat:400,600&display=swap');

        * {
            margin: 0;
            font-family: Montserrat, sans-serif;
        }

        body {
            background-color: rgb(193, 228, 166);
            background-size: 100% 100%;
        }

        /* Header */

        .header {
            background-color: rgb(172, 196, 116);
            width: 100%;
            height: 70px;
            display: flex;
            justify-content: space-between;
        }

        /* Title */

        .header-title-container {
            width: 30%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            margin-left: 1.5rem;
        }

        .header-title-container a {
            text-decoration: none;
            color: rgb(17, 17, 17);
        }

        /* Navbar */

        .navbar {
            width: 50%;
            display: flex;
            font-size: 1.2rem;
        }

        .navbar-button {
            height: 100%;
            width: 25%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-decoration: none;
            color: rgb(17, 17, 17);
        }

        .navbar-button:hover {
            background-color: rgb(193, 228, 166);
            cursor: pointer;
        }
        /* Header end */

    </style>
    <!-- Header -->
    <header class="header">
        <div class="header-title-container">
            <a href="{% url 'APP-home' %}"><h1>MealShare</h1></a>
        </div>
        <div class="navbar">
            {% comment %}<a href="#" class="navbar-button"><p>Mine annonser</p></a>{% endcomment %}
            {% if user.is_authenticated %}
                <a class="navbar-button" href="{% url 'APP-home' %}">Hjem</a>
                <a href="{% url 'middag-create' %}" class="navbar-button"><p>Ny annonse</p></a>
                <a class="navbar-button" href="{% url 'messages' %}">Meldinger</a>
                <a class="navbar-button" href="{% url 'profile' %}">Profil</a>
                <a class="navbar-button" href="{% url 'logout' %}">Logg ut</a>
            {% else %}
                <a class="navbar-button" href="{% url 'login' %}">Logg inn</a>
                <a class="navbar-button" href="{% url 'register' %}">Registrer</a>
            {% endif %}
        </div>
        {% comment %} <div class="navbar navbar-right">
        </div> {% endcomment %}
    </header>
    <!-- Header end -->
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert" alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% block content %}{% endblock %}
            </div>
            <!--
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Sidebar</h3>
                    <p>Her kommer filtreringsmuligheter</p>
                </div>
            </div>
            --->
        </div>
    </main>
    <script src="{% static '/js/create-post.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
</body>
</html>

APP/templates/APP/home.html
{% extends "APP/base.html" %}
{% load static %}

{% block content %}
    <div id="contentDiv">
        <div id="messages_header">
            <h1 class="meldingsheader">Annonser</h1>
        </div>
    </div>
    {% for Middag in middager %}
        <a href="{% url 'middag-detail' Middag.id %}">
            <article class="middagsannonse">
                <div class="middags-content">
                    <div class="article-metadata">
                        <a class="mr-2" href="{% url 'profile' %}">{{ Middag.author }}</a>
                        <small class="text-muted">{{ Middag.date_posted|date:"F d, Y" }}</small>
                    </div>
                    <h2><a class="article-title" href="{% url 'middag-detail' Middag.id %}">{{ Middag.title }}</a></h2>
                    <p class="article-content">{{ Middag.content }}</p>
                </div>
            </article>
        </a>
    {% endfor %}

{% endblock content %}

APP/templates/APP/middag_confirm_delete.html
{% extends "APP/base.html" %}

{% block content %}
    <div class="content-section">
        <form id="confirmForm" method="POST">
            <div id="confirmContent">
                {% csrf_token %}
                <fieldset id="delete_legend" class="form-group">
                    <h2>Er du sikker på at du vil slette denne middagen: '{{ object.title }}'?</h2>
                </fieldset>
                <div id="confirmButtons-container">
                    <button class="confirmPage-buttons" class="btn btn-outline-info" type="submit">Ja, slett</button>
                    <a class="confirmPage-buttons" href="{% url 'middag-detail' object.id %}"><p>Nei, gå tilbake</p></a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

APP/templates/APP/middag_confirm_join.html
{% extends "APP/base.html" %}

{% block content %}
    <div class="content-section">
        <form id="confirmForm" method="POST">
            <div id="confirmContent">
                {% csrf_token %}
                <fieldset id="delete_legend" class="form-group">
                    <h2>Er du sikker på at du vil melde deg på denne middagen: '{{ object.title }}'?</h2>
                </fieldset>
                <div id="confirmButtons-container">
                    <button class="confirmPage-buttons" class="btn btn-outline-info" type="submit">Ja, meld meg på</button>
                    <a class="confirmPage-buttons" href="{% url 'middag-detail' object.id %}"><p>Nei, gå tilbake</p></a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

APP/templates/APP/middag_detail.html
{% extends "APP/base.html" %}
{% load static %}

{% block content %}
    <article class="content-section">
        <div class="media-body">
            <div class="meta-container">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'profile' %}">{{ object.author }}</a>
                    <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
                </div>
                {% if object.author == user %}
                <div class="delete-button-container">
                    <a class="delete-button" href="{% url 'middag-update' object.id %}"><p>Endre</p></a>
                    <a class="delete-button" href="{% url 'middag-delete' object.id %}"><p>Slett</p></a>
                </div>
                {% endif %}
                {% if object.author != user %}
                <div class="delete-button-container">
                    <a class="join-button" id="join-button"><p>Meld meg på</p></a>
                </div>
                {% endif %}
            </div>
            <div class="article-content">
                <div class="title-and-description">
                    <h2><a class="article-title">{{ object.title }}</a></h2><br>
                    <p class="article-content">{{ object.content }}</p>
                </div>
                <div class="various-content">
                    <p class="article-content">Antall gjester: {{ object.guests }}</p>
                    <p class="article-content">Dele utgifter: {{ object.sharing }}</p>
                    <p class="article-content">Allergener: {{ object.allergener }}</p>
                    <p class="article-content">Kostnad: {{ object.sharing_cost }}</p>
                    <p class="article-content">Adresse: {{  object.address }}</p>
                    <p class="article-content">Postnr: {{  object.postnr }}, {{  object.poststed }} </p>
                    <p class="article-content">Dato: {{  object.date_of_dinner|date:"F d, Y H:i"  }} </p>
                </div>
            </div>

        </div>
    </article>
    <script src="{% static '/js/join-dinner.js' %}"></script>
{% endblock %}

APP/templates/APP/middag_form.html
{% extends "APP/base.html" %}
{% load static %}
{% block content %}
    <!-- Create post -->
    <div id="create-post-container">

        <form method="POST">
            {% csrf_token %}
            <h3>OPPRETT MIDDAG</h3>
            <!-- Title input -->
            <div class="input-container" id="create-post-title-container">
                <label for="title">Tittel
                    <div> {{ form.title }} </div>
                </label>
            </div>
            <!-- Description input -->
            <div class="input-container" id="create-post-description-container">
                <label for="content">Beskrivelse
                    <div> {{ form.content }} </div>
                </label>
            </div>
            <!-- Address input -->
            <div class="input-container" id="create-post-address-container">
                <div id="create-post-address">
                    <label for="address">Gate
                        <div> {{ form.address }} </div>
                    </label>
                    <label for="postnr">Postnr
                        <div> {{ form.postnr }} </div>
                    </label>
                    <label for="poststed">Poststed
                        <div> {{ form.poststed }} </div>
                    </label>
                </div>
            </div>
            <!-- Allergies input -->
            <div class="input-container" id="create-post-allergies-container">
                <label for="allergener">Allergener
                    <div id="create-post-allergies">
                        {{ form.allergener }}
                    </div>
                </label>
            </div>
            <!-- Share? -->
            <div class="input-container" id="create-post-share-container">
                <div id="share">
                    <label for="sharing">Ønsker du å dele utgiftene?</label>
                        <div id="create-post-share"> {{ form.sharing }} </div>

                </div>
                <div id="amount-container">
                    <label for="sharing_cost" class="hidden">Kostnader (NOK):</label>
                        <div> {{ form.sharing_cost }} </div>

                </div>
            </div>
            <!-- Date and Guest limit input -->
            <div class="input-container" id="data-and-guest-limit-container">
                <div id="date">
                    <label for="date_of_dinner">Når skal middagen ta sted?</label>
                        {{ form.date_of_dinner }}

                </div>
                <div id="create-post-max-container">
                    <label for="guests">Antall gjester:</label>
                        {{ form.guests }}

                </div>

            </div>
            <!-- Submit button -->
            <div id="create-post-button">
                <button type="submit" onclick="calculateCost()">Submit</button>
            </div>
        </form>
    </div>
    <!-- Create post end -->
    <script>
        function addPlaceholder(){
            var address = document.getElementById('id_address');
            var postnr = document.getElementById('id_postnr');
            var poststed = document.getElementById('id_poststed');
            var date_dinner = document.getElementById('id_date_of_dinner');
            address.placeholder = "Nordre gate 1";
            postnr.placeholder = "7011";
            poststed.placeholder = "Trondheim";
            date_dinner.placeholder = "2021-03-01 20:00"
        }
        addPlaceholder()

    </script>
    <script src="{% static '/js/create-post.js' %}"></script>
{% endblock content %}

users/templates/users/logout.html
{% extends "APP/base.html" %}
{% block content %}
    <h2 style="margin:1rem;">Du har blitt logget ut.</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}" style="text-decoration: none; color: rgb(17, 17, 17);margin-left: 1rem;">Logg inn igjen</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/messages.html
{% extends "APP/base.html" %}

{% block content %}
    <div id="contentDiv">
        <div id="messages_header">
            <h1 class="meldingsheader">Mine meldinger</h1>
            <a class="send_button" href="{% url 'send_message' %}">Send melding</a>
        </div>
    </div>
    {% for Message in messages %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'profile' %}">{{ Message.author }}</a> til
                    <small class="text-muted">{{ Message.to_user }}</small>
                </div>
                <h2><a class="article-title" href="#">{{ Message.title }}</a></h2>
                <p class="article-content">{{ Message.message }}</p>
            </div>
        </article>
    {% endfor %}

{% endblock %}

users/templates/users/profile.html
{% extends "APP/base.html" %}


{% block content %}
<div id="profile-box">
    <h2 id="profile-title">PROFIL</h2>
    <div class="info-box">
        <h3>Brukernavn</h3> 
        <p>{{ user.username }}</p>
    </div>
    <div class="info-box">
        <h3>Fullt navn</h3>
        <p>Ola Nordmann</p>
    </div>
    <div class="info-box">
        <h3>Allergier</h3>
        <p>Egg, Gluten</p>
    </div>
    <div class="info-box">
        <h3>Adresse</h3>
        <p>Bakkegata 1, 7030 Trondheim</p>
    </div>
    <div class="info-box">
        
    </div>
</div>
    
{% endblock content %}

users/templates/users/register.html
{% load static %}

<!DOCTYPE html>
<html lang="no">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static '/css/register.css' %}">
        <title>Registrer bruker</title>
        <script data-dapp-detection="">
            !function(){let e=!1;function n(){if(!e){const n=document.createElement("meta");n.name="dapp-detected",document.head.appendChild(n),e=!0}}if(window.hasOwnProperty("ethereum")){if(window.__disableDappDetectionInsertion=!0,void 0===window.ethereum)return;n()}else{var t=window.ethereum;Object.defineProperty(window,"ethereum",{configurable:!0,enumerable:!1,set:function(e){window.__disableDappDetectionInsertion||n(),t=e},get:function(){if(!window.__disableDappDetectionInsertion){const e=arguments.callee;e&&e.caller&&e.caller.toString&&-1!==e.caller.toString().indexOf("getOwnPropertyNames")||n()}return t}})}}();
        </script>

    </head>
    <body>
        <div id="id_pageContent">
            <div id="id_leftContent">
                <img id="id_foodImg" src="{% static '/img/sharingFoodCropped.jpg' %}" max-height=640 max-width=1476 alt="Image: Birdview photograph of dinnertable and multiple hands reaching for food.">
                <!--
                ## Evt. plass til logo og/eller brandname, venstre div oppå bildet
                <h1 id="id_brandName">MealShare</h1>
                <img id="id_logoImg" src="{% static '/img/logo.png' %}" max-height=200 max-width=200 alt="Image: Green logo of a fork and a knife with a circle around.">
                -->
            </div>
            
            <div id="rightContent">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Registrer bruker</legend>
                        <div id="id_setName" class="inputset">
                            <!-- Username -->
                            <div id="id_div_username" class="form-group">
                                <label for="id_username" class=" requiredField">Brukernavn<span class="asteriskField">*</span></label>
                                <div class="">
                                    {{ form.username }}
                                    <small id="id_hint_username" class="form-text text-muted">Required. 150 characters or fewer. Letters, digits and @ . + - _ only.</small>
                                </div>
                            </div>
                            <!-- Full name -->
                            <div id="id_div_name" class="form-group">
                                <label for="id_name" class=" requiredField">Fullt navn<span class="asteriskField">*</span></label>
                                <div class="">
                                    {{ form.name }}
                                </div>
                            </div>
                        </div>     

                        <div id="id_setAllergyAddress" class="inputset">
                            <!-- Allergy -->
                            <div id="id_div_allergies" class="form-group">
                                <label for="id_allergies" class=" requiredField">Allergener<span class="asteriskField">*</span>
                                    <div class="">
                                        {{ form.allergies }}
                                    </div>
                                </label>
                            </div>
                            <!-- Address -->
                            <div id="id_div_address" class="form-group">
                                <label id="id_adressLabel" for="id_address" class=" requiredField">Gatenavn og husnummer<span class="asteriskField">*</span></label>
                                <div class="">
                                    {{ form.address }}
                                </div>
                            </div>
                        </div>

                        <div id="id_setPost" class="inputset">
                            <!-- Post nr. -->
                            <div id="id_div_postnr" class="form-group">
                                <label for="id_postnr" class=" requiredField">Postnummer<span class="asteriskField">*</span></label>
                                <div class="">
                                    {{ form.postnr }}
                                </div>
                            </div>
                            <!-- Poststed -->
                            <div id="id_div_poststed" class="form-group">
                                <label for="id_poststed" class=" requiredField">Sted<span class="asteriskField">*</span></label>
                                <div class="">
                                    {{ form.poststed }}
                                </div>
                            </div>
                        </div>

                        <div id="id_setPassword" class="inputset">
                            <!-- Password -->
                            <div id="id_div_password1" class="form-group">
                                <label for="id_password1" class=" requiredField">Passord<span class="asteriskField">*</span></label>
                                <div class="">
                                    {{ form.password1 }}
                                </div>
                            </div>
                            <!-- Password confirmation -->
                            <div id="id_div_password2" class="form-group">
                                <label for="id_password2" class=" requiredField">Bekreft passord<span class="asteriskField">*</span></label>
                                <div class="">
                                    {{ form.password2 }}
                                    <small id="id_hint_password2" class="form-text text-muted">Enter the same password as before, for verification.</small>
                                </div>
                            </div>
                        </div>
                    </fieldset>

                    <!-- Sign up submit-button -->
                    <div id="id_signUpButton" class="form-group">
                        <button class="btn btn-outline-info" type="submit">Registrer</button>
                        <small>
                            {% if form.errors %}
                                <p>Det er noe feil med skjemaet prøv igjen!</p>
                            {% endif %}
                        </small>
                    </div>
                </form>

                <!-- Login instead -->
                <div id="id_signInText" class="border-top pt-3">
                    <small class="text-muted">
                        Har du allerede en bruker? <a class="ml-2" href="{% url 'login' %}">Logg inn</a>
                    </small>
                </div>
            </div>
        </div>




        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <iframe id="nr-ext-rsicon" style="position: absolute; display: none; width: 50px; height: 50px; z-index: 2147483647; border-style: none; background: transparent;"></iframe>
    </body>
</html>

users/templates/users/send_message.html
{% extends "APP/base.html" %}

{% block content %}
<div id="send_message_box">
    <form id="send_message_form" action="" method="post">
        <br>
        <h1>Send melding</h1><br>
        {% csrf_token %}
            {{ form }}
        <input type="submit" value="Submit">
    </form>
</div>
{% endblock %}
    